const {DEFAULT_DIMENSIONS,
    DEFAULT_LEG_DIMENSIONS,
    DEFAULT_BODY_DIMENSIONS,
    DEFAULT_POSE,
    DEFAULT_PATTERN_PARAMS,
    DEFAULT_GAIT_PARAMS,
    DEFAULT_IK_PARAMS,
    DEFAULT_SERVO_POSE_VALUE,
    SERVO_LINK_PINS} = require("./hexapodParams");


const GAMEPAD_VENDOR_ID = 1133;
const GAMEPAD_PRODUCT_ID = 49695;    

module.exports =  {
    DEFAULT_DIMENSIONS: DEFAULT_DIMENSIONS,
    DEFAULT_LEG_DIMENSIONS: DEFAULT_LEG_DIMENSIONS,
    DEFAULT_BODY_DIMENSIONS: DEFAULT_BODY_DIMENSIONS,
    DEFAULT_POSE: DEFAULT_POSE,
    DEFAULT_PATTERN_PARAMS: DEFAULT_PATTERN_PARAMS,
    DEFAULT_GAIT_PARAMS: DEFAULT_GAIT_PARAMS,
    DEFAULT_IK_PARAMS: DEFAULT_IK_PARAMS,
    DEFAULT_SERVO_POSE_VALUE: DEFAULT_SERVO_POSE_VALUE,
    SERVO_LINK_PINS: SERVO_LINK_PINS,

    GAMEPAD_VENDOR_ID: GAMEPAD_VENDOR_ID,
    GAMEPAD_PRODUCT_ID: GAMEPAD_PRODUCT_ID
}
